# Generated by Django 5.1.3 on 2024-12-11 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_training_triningprodram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approach_order', models.PositiveIntegerField()),
                ('reps', models.PositiveIntegerField()),
                ('weight', models.FloatField(null=True)),
                ('exercice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.exercice')),
                ('training_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.training')),
            ],
        ),
        migrations.AddField(
            model_name='training',
            name='exercices',
            field=models.ManyToManyField(related_name='trainigs', through='main.Approach', to='main.exercice'),
        ),
    ]
