# Generated by Django 5.1.3 on 2024-12-11 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_approach_training_exercices'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TriningProdram',
            new_name='TrainingProdram',
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')])),
                ('time', models.TimeField()),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.trainingprodram')),
                ('training_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.training')),
            ],
        ),
    ]
